dqn:
  deepset:
    fc1_dims: 32
    fc2_dims: 128
    embedding_dims: 64
  final_fc_dims: 32
  dropout: 0.1

# # Small numbers for pipeline test only
# dqn:
#   deepset:
#     fc1_dims: 16
#     fc2_dims: 32
#     embedding_dims: 64
#   final_fc_dims: 8
#   dropout: 0.1

train:
  epochs: 50
  lr: 0.0005
  batch_size: 64
  gamma: 0.99
  epsilon:
    init: 1.0
    min: 0.001
    decay: 0.99
    decay_interval: 50  # Steps per epsilon decay
