dqn:
  deepset:
    fc1_dims: 32
    fc2_dims: 64
    embedding_dims: 64
  final_fc_dims: 32
  dropout: 0.1

# # Small numbers for pipeline test only
# dqn:
#   deepset:
#     fc1_dims: 16
#     fc2_dims: 32
#     embedding_dims: 64
#   final_fc_dims: 8
#   dropout: 0.1

train:
  epochs: 50
  epochs_freeze: 3  # Stop learning, only collect experience and run evaluation
  train_interval: 1  # Train every n episodes
  lr: 0.0005
  batch_size: 64
  gamma: 0.995
  epsilon:
    init: 1.0
    min: 0.005
    decay: 0.997
    decay_interval: 50  # Steps per epsilon decay
  reward:
    alpha: 0.25
    arrival_bonus: 1.0
    drop_penalty: 1.0
