satellite:
  # Height config in kilometers
  height: 500
  n_satellites: 1000
  # Random mu for different Poisson processes
  mu:
    lower: 100
    upper: 200

physics:
  r_earth: 6400 # km
  c: 300000 # km/s
  simulation_time: 10 # seconds