satellite:
  # Height config in kilometers
  height: 600
  n_satellites: 1200
  d_max: 2000 # km
  angle_limit: 75 # Degree, should be less than 90
  n_neighbours: 10 # Maximum number of nearest neighbours to consider per satellite
  # Random mu for different Poisson processes
  mu:
    lower: 100
    upper: 125
    start_scale: 40.0  # Make S0 generate more packages to simulate congestion. Should be >> 1.0
  queue_limit: 25  # Maximum queue capacity per satellite

physics:
  r_earth: 6400 # km
  c: 300000 # km/s
  simulation_time: 0.05 # seconds

baseline_reward:
  alpha: 0.25
  arrival_bonus: 10.0
  drop_penalty: 10.0