satellite:
  height: 600 # km
  n_satellites: 1000
  d_max: 2000 # km
  angle_limit: 75 # Degree, should be less than 90
  n_neighbours: 7 # Maximum number of nearest neighbours to consider per satellite
  # Random mu for different Poisson processes
  mu:
    lower: 40.0
    upper: 60.0
    start_scale: 25.0  # Make S0 generate more packets to simulate congestion. Should be >> 1.0
  queue_limit: 15  # Maximum queue capacity per satellite

physics:
  r_earth: 6400 # km
  c: 300000 # km/s
  simulation_time: 0.15 # seconds
