satellite:
  # Height config in kilometers
  height: 600
  n_satellites: 1500
  d_max: 2000 # km
  angle_limit: 75 # Degree, should be less than 90
  n_neighbours: 10 # Maximum number of nearest neighbours to consider per satellite
  # Random mu for different Poisson processes
  mu:
    lower: 30.0
    upper: 40.0
    start_scale: 30.0  # Make S0 generate more packets to simulate congestion. Should be >> 1.0
  queue_limit: 10  # Maximum queue capacity per satellite

physics:
  r_earth: 6400 # km
  c: 300000 # km/s
  simulation_time: 0.1 # seconds
